[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
